from extractors.pdf_to_text_extractor.methods.SegmentSelectorDateParserMethod import SegmentSelectorSameInputOutputMethod
from extractors.text_to_text_extractor.methods.NerLastAppearanceMethod import NerLastAppearanceMethod


class SegmentSelectorNerLastAppearanceMethod(SegmentSelectorSameInputOutputMethod):

    SEMANTIC_METHOD = NerLastAppearanceMethod
