from extractors.pdf_to_text_extractor.methods.SegmentSelectorDateParserMethod import SegmentSelectorSameInputOutputMethod
from extractors.text_to_text_extractor.methods.NerFirstAppearanceMethod import NerFirstAppearanceMethod


class SegmentSelectorNerFirstAppearanceMethod(SegmentSelectorSameInputOutputMethod):

    SEMANTIC_METHOD = NerFirstAppearanceMethod
