from extractors.pdf_to_text_extractor.methods.SegmentSelectorDateParserMethod import \
    SegmentSelectorSameInputOutputMethod
from extractors.text_to_text_extractor.methods.RegexSubtractionMethod import RegexSubtractionMethod


class SegmentSelectorRegexSubtractionMethod(SegmentSelectorSameInputOutputMethod):

    SEMANTIC_METHOD = RegexSubtractionMethod