version: "3.8"
services:
  cloud_pdf_metadata_extraction_api:
    extends:
      file: docker-compose.yml
      service: pdf_metadata_extraction_api
    env_file: .env.cloud
  cloud_pdf_metadata_extraction_worker:
    extends:
      file: docker-compose.yml
      service: pdf_metadata_extraction_worker
    env_file: .env.cloud
  cloud_mongo_metadata_extraction:
    extends:
      file: docker-compose.yml
      service: mongo_metadata_extraction
  cloud_redis_metadata_extraction:
    extends:
      file: docker-compose.yml
      service: redis_metadata_extraction
networks:
  pdf_metadata_extraction_network:

volumes:
  data: