include:
  - docker-compose.base.yml

services:
  pdf_metadata_extraction_worker:
    container_name: pdf_metadata_extraction_worker
    init: true
    entrypoint: [ "celery", "-A", "drivers.distributed_worker.distributed_no_gpu", "worker", "--loglevel=info", "--concurrency=1", "--pool=solo" ]
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/models_data
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_DSN=${SENTRY_DSN:-}
    network_mode: host
    env_file: .env
