include:
  - docker-compose.yml

services:
  pdf_metadata_extraction_worker:
    entrypoint: [ "celery", "-A", "drivers.distributed_worker.distributed_gpu", "worker", "--beat", "--loglevel=info", "--concurrency=1", "--pool=solo"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
