version: "3.8"
services:
  pdf_metadata_extraction_api:
    extends:
      file: docker-compose.yml
      service: pdf_metadata_extraction_api
    depends_on:
      - mongo_metadata_extraction
      - pdf_metadata_extraction_worker

  pdf_metadata_extraction_worker:
    extends:
      file: docker-compose.yml
      service: pdf_metadata_extraction_worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    depends_on:
      - mongo_metadata_extraction

  mongo_metadata_extraction:
    extends:
      file: docker-compose.yml
      service: mongo_metadata_extraction

volumes:
  data: