# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Free up space
        run: make free-up-space

      - name: Install venv
        run: make install-venv

      - name: Lint with black
        run: make check-format

      - name: Start service
        run: make start-detached

      - name: Check API ready
        uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:5056
          method: GET
          expected-status: 200
          timeout: 240000
          interval: 500

      - name: Wait for queues
        run: make wait-for-queues

      - name: Test with unittest
        run: make test

      - name: Stop service
        run: make stop

      - name: Replace variables for cloud
        run: mv .env.cloud .env

      - name: Start service
        run: make start-detached

      - name: Check API ready
        uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: http://localhost:5056
          method: GET
          expected-status: 200
          timeout: 240000
          interval: 500

      - name: Test cloud
        run: make test-cloud

